#lang sicp
"Ex. 1.9"
;Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements
;its argument by 1. Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?
(define (sum a b)
  (if (= a 0) b (inc (sum (dec a) b))))

;recursive process, as it expands and requires to keep 5 inc procedures to perform later in the stack, once a variable a decreases to 0

(define (plus a b)
  (if (= a 0) b (plus (dec a) (inc b))))

;iterative process, as it only requires to store values of 2 variables to keep track of current iteration

(sum 4 5)
(plus 4 5)
(newline)

"Ex. 1.10"
;Ackermann's function
(define (A x y)
  (cond ((= y 0) y)
        ((= x 0) (* 2 y))
        ((= y 1) 2)
        (else (A (- x 1) (A x (- y 1))))))

;What are the values of the following expressions?
(A 1 10)
;2^10
(A 2 4)
;2^16
(A 3 3)
;2^16
(newline)

;Give concise mathematical definitions for the functions computed by the procedures below for positive integer values of n
(define (f n) (A 0 n))
;2n
(define (g n) (A 1 n))
;2^n
(define (h n) (A 2 n))
;2 if n = 1
;2^(2^(2^...n times)) if n>1

(f 8)
(g 11)
(h 3)
